# Generated by Django 4.0 on 2022-12-23 06:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField()),
                ('organization_id', models.CharField(max_length=20, unique=True)),
                ('organization_name', models.CharField(max_length=255, unique=True)),
                ('established_date', models.DateField()),
                ('organization_email', models.EmailField(max_length=255, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_category', models.CharField(max_length=200, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Organization Category',
            },
        ),
        migrations.CreateModel(
            name='OrganizationExEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed_by', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('organization_joined_date', models.DateField(default=django.utils.timezone.now)),
                ('role', models.CharField(default='Ex-employee', max_length=15)),
                ('removed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name_plural': 'Organization Ex-employee',
            },
        ),
        migrations.CreateModel(
            name='OrganizationEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('organization_joined_date', models.DateField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('Ex-employee', 'Ex-employee')], default='Employee', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_org_admin', models.BooleanField(default=False)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name_plural': 'Organization Employee',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organizationcategory'),
        ),
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=255)),
                ('organization_id', models.IntegerField()),
                ('is_org_admin', models.BooleanField(default=False)),
                ('is_create', models.BooleanField(default=False)),
                ('is_list', models.BooleanField(default=False)),
                ('is_update', models.BooleanField(default=False)),
                ('is_retrieve', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organizationemployee')),
            ],
            options={
                'verbose_name_plural': 'Organization Employee Permissions',
            },
        ),
    ]
